name: minigun_client_dart
description: An example for an client in client/server project.
version: 1.0.0
homepage: https://github.com/taworn-ta7/examples.minigun
repository: https://github.com/taworn-ta7/examples.minigun

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging: ^1.0.2
  json_annotation: ^4.4.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
